apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: blakyaks-backend
  name: blakyaks-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-v1
  namespace: blakyaks-backend
---
apiVersion: v1
kind: Service
metadata:
  name: api-v1
  namespace: blakyaks-backend
spec:
  selector:
    app: api-v1
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v1
  namespace: blakyaks-backend
  labels:
    app: api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-v1
  template:
    metadata:
      labels:
        app: api-v1
    spec:
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.7.8
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9091'
            - name: 'NAME'
              value: 'api-v1'
            - name: 'MESSAGE'
              value: 'Response from API v1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: blakyaks-backend
spec:
  selector:
    matchLabels:
      app: curl
  replicas: 1
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ["/bin/sh"]
        args: ["-c", "sleep 1d"]