apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: blakyaks-frontend
  name: blakyaks-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: blakyaks-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: blakyaks-frontend
spec:
  selector:
    app: web
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: blakyaks-frontend
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nicholasjackson/fake-service:v0.7.8
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'